# Generated by Django 3.2 on 2021-05-18 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExperienceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exp_type', models.CharField(choices=[('W', 'Work'), ('E', 'Experience'), ('I', 'Internship')], max_length=100)),
                ('experience_name', models.CharField(max_length=200)),
                ('organization_name', models.CharField(max_length=200)),
                ('exp_date', models.CharField(max_length=200)),
                ('org_location', models.CharField(max_length=500)),
                ('learning_description', models.TextField()),
                ('image', models.ImageField(upload_to='E:\\Softwares\\PyCharmProjects\\Portfolio\\media\\\\orgs\\')),
            ],
        ),
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200)),
                ('languages', models.CharField(max_length=500)),
                ('project_description', models.TextField()),
                ('image_path', models.ImageField(upload_to='E:\\Softwares\\PyCharmProjects\\Portfolio\\media\\')),
                ('link', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='SkillsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=200)),
                ('skill_icon', models.TextField()),
                ('skill_master_percentage', models.IntegerField()),
                ('skill_description_link', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=200)),
                ('user_email', models.CharField(max_length=500)),
                ('rating', models.IntegerField(max_length=1)),
                ('experience', models.TextField()),
                ('reply', models.TextField()),
            ],
        ),
    ]
