# Generated by Django 3.2 on 2021-07-06 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galleryitem',
            name='image_path',
        ),
    ]
